### ISSUE TITLE
Unicode support missing

### ISSUE THREAD

**Issue by rblaakmeer** [Deepakchawla/Mobile-Phone-Dataset-GSMArena#3]
The script crashes when it encounters Unicode data.
Changing line 134 to **with open(self.absolute_path + '/' + brand[0].title() + ".csv", "w",encoding='utf-8-sig',newline='')  as file:** will add Unicode support.

**Comment by Deepakchawla** [comment]
You can clone the repo and commit the changes and create the pull request then I will merge the code.
