### ISSUE TITLE
'pwd' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by bugrevealingbme** [Deepakchawla/Mobile-Phone-Dataset-GSMArena#5]
GSMArenaDataset directory already exists
Traceback (most recent call last):
  File "gsmarena_scraping.py", line 149, in <module>
    obj.save_specification_to_file()
  File "gsmarena_scraping.py", line 121, in save_specification_to_file
    files_list = self.check_file_exists()
  File "gsmarena_scraping.py", line 115, in check_file_exists
    return os.listdir(self.absolute_path)
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: '/GSMArenaDataset'

**Comment by bl-deepakchawla** [comment]
@bugrevealingbme you have to delete the GSMArenaDataset folder and run again script.

**Comment by Deepakchawla** [comment]
@bugrevealingbme you have to delete the GSMArenaDataset folder and run again script.

**Comment by voogarix** [comment]
Hi.  Same problem happend on my Windows 10 system. Already deleted GSMArenaDataset folder, tried run with/without admin rights but nothing change. Is there another solution?

**Comment by voogarix** [comment]
C:\Users\user\Desktop\Mobile-Phone-Dataset-GSMArena-master>python gsmarena_scraping.py
'pwd' is not recognized as an internal or external command,
operable program or batch file.
Creating  GSMArenaDataset  Folder....
Folder Created.
Traceback (most recent call last):
  File "gsmarena_scraping.py", line 149, in <module>
    obj.save_specification_to_file()
  File "gsmarena_scraping.py", line 121, in save_specification_to_file
    files_list = self.check_file_exists()
  File "gsmarena_scraping.py", line 115, in check_file_exists
    return os.listdir(self.absolute_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/GSMArenaDataset'

**Comment by voogarix** [comment]
solved the problem. pwd is linux command. for run in Windows you have to change os.popen('pwd') to os.popen('echo %cd%')

**Comment by Deepakchawla** [comment]
@voogarix issue solved, now I am closing the issue.
