### ISSUE TITLE
Not completely native Python code since it uses pwd, thus not working on Windows

### ISSUE THREAD

**Issue by opus-x** [Deepakchawla/Mobile-Phone-Dataset-GSMArena#7]
Please change the following line:
line 20: `self.absolute_path = os.popen('pwd').read().strip() + '/' + self.new_folder_name  # It create the absolute path of the GSMArenaDataset folder.`

new code:
`self.absolute_path = os.path.dirname(os.path.realpath(__file__)) + '/' + self.new_folder_name  # It create the absolute path of the GSMArenaDataset folder.`

**Comment by krm1337** [comment]
This also works:
self.absolute_path = os.getcwd() + '/' + self.new_folder_name  +'/' # It create the absolute path of the GSMArenaDataset folder.

**Comment by Sahil-Ajmera** [comment]
I have added a PR to update the code https://github.com/Deepakchawla/Mobile-Phone-Dataset-GSMArena/pull/10
Hopefully that fixes things.

**Comment by Deepakchawla** [comment]
code has been updated now guys will not get the issue.
